grepclips now requires explicit --pattern --help now works properly

diff --git a/scripts/bin/grepclips b/scripts/bin/grepclips
--- a/scripts/bin/grepclips
+++ b/scripts/bin/grepclips
@@ -11,8 +11,8 @@ while :
 do
 case $1 in
 --help | -\?)
-echo "usage:"
-echo 'grepclips -p "search phrase" -P /path/to/dir -A "context lines after" -B "context lines before"'
+usage:
+grepclips -p "search phrase" -P /path/to/dir -A "context lines after" -B "context lines before"
 exit 0  # This is not an error, the user requested help, so do not exit status 1.
 ;;
 -p|--pattern)
@@ -61,6 +61,11 @@ shift
 
 esac
 done
+
+if [ ! "$pattern" ]; then
+   echo "ERROR: option '-p [pattern]' not given. See --help" >&2
+  exit 1
+fi
 
 grep -r -l -i "$pattern" "$path" | while read fn
 do
